// ── Step: Format Backlog ─────────────────────────────────────────────────
// Stage 6 of req-decompose: Synthesize the full decomposition hierarchy into
// a clean, printable BACKLOG.md — from requirement → EARS → stories → BDD
// scenarios → TDD task list. The living decomposition artifact.

import { retry } from "../gates/index.js";
import type { Step } from "../types.js";

const prompt = `
You are the Backlog Formatter. Produce a clean BACKLOG.md from the full decomposition.

Validated TDD task list:
$INPUT

Original requirement:
$ORIGINAL

Produce a structured BACKLOG.md with this hierarchy:

\`\`\`markdown
# Backlog: [requirement title]

> Generated by req-decompose pipeline

## Decomposition Hierarchy

Requirement → EARS requirements → User Stories → BDD Scenarios → TDD Tasks

---

## Story: STORY-N — [name]

**Source REQ:** REQ-X
**Splitting pattern:** [pattern used]
**Estimated size:** [hours]

### Scenario N.X: [scenario name]

- **Given:** ...
- **When:** ...
- **Then:** ...

#### TDD Task List

| # | Task | Function | Est |
|---|------|----------|-----|
| TASK-N.X.1 | [test description] | \`functionName()\` | 10 min |

---

## Summary

| Metric | Count |
|--------|-------|
| EARS Requirements | N |
| User Stories | N |
| BDD Scenarios | N |
| TDD Tasks (atomic) | N |
| Total estimated time | Xh |
\`\`\`

Write the final BACKLOG.md to disk using the write tool.
Also print the full content in a \`\`\`markdown code block.
`;

export const formatBacklog: Step = {
	kind: "step",
	label: "Format Backlog",
	tools: ["read", "bash"],
	model: "flash",
	temperature: 0,
	description:
		"Synthesize full hierarchy into a BACKLOG.md living decomposition artifact",
	prompt,
	onFail: retry,
	transform: { kind: "full" },
};
