// ── Pipeline: GitHub PR Review ────────────────────────────────────────────
// End-to-end automated PR review: reads all changed files, runs security
// and quality analysis in parallel, generates per-file inline review comments,
// synthesizes a final verdict (APPROVE / REQUEST_CHANGES / COMMENT), and
// posts the review to GitHub via the CLI.
//
// Generated by req-decompose-to-pipeline — the req-decompose-ai methodology
// was applied to produce typed execution contracts, dependency-ordered layers,
// and execution-spec.json before being assembled into this TypeScript file.
//
// Flow:
//   1. PARSE      → builder: parse 'owner/repo#number' → typed PR reference
//   2. VALIDATE   → parallel: input validation tests (5 rejection paths)
//                           + auth check (GITHUB_TOKEN present?)
//   3. FETCH META → parallel: GitHub API call (GET /pulls/{n})
//                           + auth-failure path validation
//   4. EMIT META  → builder: raw API JSON → typed PrMetadata object
//   5. FILES      → builder: fetch all changed files + diffs via GitHub CLI
//   6. REVIEW     → pool ×changed-files: per-file review (correctness, security,
//                   quality, types, tests) — all files reviewed in parallel
//   7. VERDICT    → resolver: aggregate findings → APPROVE/REQUEST_CHANGES/COMMENT
//                   → post review to GitHub via CLI
//
// Decomposition hierarchy (produced by req-decompose-ai):
//   Requirement
//     └── EARS requirements (7 testable statements)
//           └── User Stories (INVEST, business-rule sliced)
//                 └── BDD Scenarios (Given/When/Then, acceptance tests)
//                       └── Typed UNIT-N contracts (prompt-as-contract)
//                             └── Haiku-safe scored → topo sorted → execution-spec.json
//
// Preset: captain:github-pr-review
//   Load with: captain_load { action: "load", name: "captain:github-pr-review" }
//
// Agents: builder, validator, reviewer, resolver
// Steps:  extensions/captain/steps/{parse-pr-input, validate-pr-input,
//         fetch-pr-metadata-auth-check, fetch-pr-metadata-auth-failure,
//         fetch-pr-metadata-gh-call, fetch-pr-metadata-emit,
//         fetch-pr-files, review-pr-file, synthesize-pr-verdict}.ts

import {
	fetchPrFiles,
	fetchPrMetadataAuthCheck,
	fetchPrMetadataAuthFailure,
	fetchPrMetadataEmit,
	fetchPrMetadataGhCall,
	parsePrInput,
	reviewPrFile,
	synthesizePrVerdict,
	validatePrInput,
} from "../steps/index.js";
import type { Parallel, Pool, Runnable } from "../types.js";

// ── Stage 2: Parallel — input validation + auth check ───────────────────
// 5 input-rejection tests run alongside the auth-check so token presence
// is confirmed at the same time inputs are validated — no wasted round trips.

const validateAndAuth: Parallel = {
	kind: "parallel",
	steps: [validatePrInput, fetchPrMetadataAuthCheck],
	merge: { strategy: "concat" },
};

// ── Stage 3: Parallel — GitHub API call + auth-failure path ─────────────
// The actual API call and the auth-failure validation run concurrently.
// Both depend on the auth check from Stage 2.

const fetchAndValidateAuth: Parallel = {
	kind: "parallel",
	steps: [fetchPrMetadataGhCall, fetchPrMetadataAuthFailure],
	merge: { strategy: "concat" },
};

// ── Stage 6: Pool — per-file review in parallel ──────────────────────────
// Each file gets its own review pass. Pool count is set to 10 to handle
// PRs with up to 10 changed files fully in parallel; larger PRs are batched.

const reviewFilesPool: Pool = {
	kind: "pool",
	step: reviewPrFile,
	count: 10,
	merge: { strategy: "concat" },
};

// ── Pipeline Spec ────────────────────────────────────────────────────────

export const pipeline: Runnable = {
	kind: "sequential",
	steps: [
		parsePrInput, //  1️⃣  PARSE    — 'owner/repo#N' → typed PrReference
		validateAndAuth, //  2️⃣  VALIDATE — input rejection tests + GITHUB_TOKEN check
		fetchAndValidateAuth, //  3️⃣  FETCH    — GET /pulls/{n} + auth-failure path
		fetchPrMetadataEmit, //  4️⃣  EMIT     — raw JSON → typed PrMetadata
		fetchPrFiles, //  5️⃣  FILES    — gh pr diff → structured file list
		reviewFilesPool, //  6️⃣  REVIEW   — pool ×10: per-file review in parallel
		synthesizePrVerdict, //  7️⃣  VERDICT  — aggregate → APPROVE/REQUEST_CHANGES → post
	],
};
