// ── core/contract.ts — Pure contract file content builder ─────────────────
// No I/O. Takes paths, returns the string content to write.

/** Build the content for the `.pi/pipelines/captain.ts` contract file. */
export function buildContractContent(apiPath: string): string {
	return [
		"// ── Captain Pipeline API Contract ────────────────────────────────────────────",
		"// Auto-generated by the captain extension — do not edit manually.",
		"// Re-run `captain_generate` or restart pi to refresh.",
		"//",
		"// Import from this file to get full IDE autocomplete and type checking:",
		'//   import { retry, llmFast, bunTest } from "./captain.ts";',
		'//   import type { Runnable, Step } from "./captain.ts";',
		`export * from "${apiPath}";`,
	].join("\n");
}

/** Collect user-facing preset names from a list of pipeline file names. */
export function pipelineNamesFromFiles(
	fileNames: readonly string[],
): readonly string[] {
	return fileNames
		.filter(
			(f) => f !== "captain.ts" && (f.endsWith(".ts") || f.endsWith(".json")),
		)
		.map((f) => (f.endsWith(".ts") ? f.slice(0, -3) : f.slice(0, -5)));
}
