import { describe, expect, test } from "bun:test";
import { buildContractContent, pipelineNamesFromFiles } from "./contract.js";

describe("buildContractContent", () => {
	test("contains the provided apiPath in the export", () => {
		const content = buildContractContent("/some/path/api.ts");
		expect(content).toContain('export * from "/some/path/api.ts"');
	});

	test("contains the auto-generated header comment", () => {
		const content = buildContractContent("/x/api.ts");
		expect(content).toContain("Auto-generated by the captain extension");
	});

	test("contains the import example comment", () => {
		const content = buildContractContent("/x/api.ts");
		expect(content).toContain("import { retry");
	});

	test("is a single string (no undefined lines)", () => {
		const content = buildContractContent("/x/api.ts");
		expect(typeof content).toBe("string");
		expect(content.length).toBeGreaterThan(0);
	});

	test("different apiPaths produce different output", () => {
		const a = buildContractContent("/a/api.ts");
		const b = buildContractContent("/b/api.ts");
		expect(a).not.toBe(b);
	});
});

describe("pipelineNamesFromFiles", () => {
	test("strips .ts extension", () => {
		expect(pipelineNamesFromFiles(["my-pipeline.ts"])).toEqual(["my-pipeline"]);
	});

	test("strips .json extension", () => {
		expect(pipelineNamesFromFiles(["my-pipeline.json"])).toEqual([
			"my-pipeline",
		]);
	});

	test("filters out captain.ts", () => {
		expect(pipelineNamesFromFiles(["captain.ts", "foo.ts"])).toEqual(["foo"]);
	});

	test("filters out files with unknown extensions", () => {
		expect(pipelineNamesFromFiles(["readme.md", "foo.ts"])).toEqual(["foo"]);
	});

	test("handles mixed .ts and .json files", () => {
		expect(pipelineNamesFromFiles(["a.ts", "b.json", "c.ts"])).toEqual([
			"a",
			"b",
			"c",
		]);
	});

	test("returns empty array for empty input", () => {
		expect(pipelineNamesFromFiles([])).toEqual([]);
	});

	test("returns empty array when only captain.ts present", () => {
		expect(pipelineNamesFromFiles(["captain.ts"])).toEqual([]);
	});

	test("handles filenames with dots in the name", () => {
		expect(pipelineNamesFromFiles(["my.cool.pipeline.ts"])).toEqual([
			"my.cool.pipeline",
		]);
	});
});
